### PR TITLE
fix: update Plex test fixtures broken by PR #314 signature change

### PR DESCRIPTION
**Pull request by razzamatazm**
## What a user would notice

Nothing in the app changes. This is a test-only fix that unblocks CI so all 9 queued PRs (#322-#330) can merge.

## What changed

PR #314 added a `request` parameter as the first argument to `plex_login_start`. Two tests in `test_plex_enabled_guard.py` were not updated and still called it with only `session`, causing a type error at test time. In `test_plex_start_rate_limit.py`, the `_mock_request()` helper did not set `req.headers = {}`, so the `MagicMock` default for `X-Forwarded-For` was truthy and `_client_key()` returned a mock object instead of the string `"10.0.0.1"`, so the rate-limit bucket never matched the pre-seeded key and HTTP 429 was never raised.

Three-line fix across two files:

- `test_plex_enabled_guard.py`: pass `_mock_request()` as the first argument to `plex_login_start` in the two tests that were missing it (lines 80 and 91).
- `test_plex_start_rate_limit.py`: add `req.headers = {}` to `_mock_request()` so the X-Forwarded-For check returns `None` (not a truthy mock) and the correct IP string is used as the bucket key.

No production code changed.

## How it was tested

**Before:**
```
ERROR: test_start_disabled_server_raises_403 - AttributeError: 'AsyncSession' object has no attribute 'client'
ERROR: test_start_enabled_server_proceeds - AttributeError: 'AsyncSession' object has no attribute 'client'
FAIL: test_eleventh_request_returns_429 - AssertionError: HTTPException not raised
FAIL: test_different_clients_have_independent_buckets - AssertionError: HTTPException not raised
```

**After:**
```
Ran 750 tests in 3.861s
OK
```

All 4 previously failing tests now pass. Full suite: 750 tests, 0 failures.

Closes the [TODO] task: "fix: broken Plex test fixtures block all CI (HIGH)".

### CODE REVIEW

**Review by razzamatazm-cleo — APPROVED** [review]
Approve. Verified by inspection:

- test_plex_enabled_guard.py: plex_login_start signature is (request, session) at auth.py:384; the two calls now correctly pass _mock_request() as the first arg. Helper at line 34 already sets headers={}.
- test_plex_start_rate_limit.py: each _mock_request() builds a fresh MagicMock, so before the fix headers.get("X-Forwarded-For") returned a truthy mock and _client_key returned a per-request mock object, so the bucket never accumulated and 429 never fired. Adding headers={} makes .get() return None, _client_key falls back to the host string "127.0.0.1" shared across the loop, so the 11th request raises 429. The different-clients test gets distinct host strings, keeping buckets independent.

Test-only change, no production code, minimal diff, plain-English body with before/after evidence, no em dashes. Could not run the suite in my clone (no fastapi installed) but the logic is correct and the PR shows 750/750 green. Looks good.
